INSERT INTO USER_ENTITY (EMAIL, PASSWORD) VALUES ('test123@gmail.com', '$2a$10$N97lS2a6Bje23Ljjs6x4i.caq6LGhFatoq.UHZx349ygZ5w8mdq2m');
INSERT INTO USER_ENTITY (EMAIL, PASSWORD) VALUES ('test456@gmail.com', '$2a$10$N97lS2a6Bje23Ljjs6x4i.caq6LGhFatoq.UHZx349ygZ5w8mdq2m');

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) values (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) values (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) values (2, 2);